services:
  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootPass
      - MYSQL_DATABASE=tikets
  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  mysql_data: